---
- hosts: localhost
  gather_facts: no
  become: no
  roles:
    - gen_key_pair
    - run_terraform

- hosts: ec2
  gather_facts: no
  become: yes
  roles:
    - linux_pre

- hosts: app
  become: yes
  roles:
    - deploy_app
    - { role: docker_compose, tpl_prefix: "app"}