---
- name: "Wait for connection"
  wait_for_connection:

- name: "Gather facts"
  setup:

- name: "Update linux"
  package:
    name: "*"
    state: "present"
    force_apt_get: true

- name: "Install required packages"
  package:
    name: "{{ item }}"
    state: "present"
    force_apt_get: true
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg2"
    - "software-properties-common"
    - "python-docker"

- name: "Add docker-ce apt signing key"
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: "Add docker-ce repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['lsb']['codename'] }} stable"
    state: present

- name: "Install docker-ce package"
  package:
    name: "docker-ce"
    state: "present"
    force_apt_get: true

- name: "Ensure docker service is started and enabled"
  service:
    name: "docker"
    state: started
    enabled: true

- name: "Install docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['machine'] }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: "Make sure docker-compose dir exist"
  file:
    path: "docker-compose/"
    state: "directory"
