- name: "Execute terraform to create infrastructure"
  terraform:
    project_path: "{{ playbook_dir }}/terraform/"
    state: "present"
    variables:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      public_key: "{{ lookup('file', '{{ playbook_dir }}/files/id_rsa.pub') }}"
      project_name: "{{ project_name }}"
      vpc_cidr: "{{ vpc_cidr }}"
      subnet1_cidr: "{{ subnet1_cidr }}"
      subnet2_cidr: "{{ subnet2_cidr }}"
    force_init: yes
  register: terraform_output

- name: "Add EC2 instances to the inventory in runtime"
  add_host:
    hostname: "{{ item['hostname'] }}"
    groups: "{{ item['groups'] }}"
    private_ip: "{{ item['private_ip'] }}"
  with_items:
    - { hostname: "{{ terraform_output['outputs']['app-public-ip']['value'] }}", private_ip: "{{ terraform_output['outputs']['app-private-ip']['value'] }}", groups: "app" }
    - { hostname: "{{ terraform_output['outputs']['db-master-public-ip']['value'] }}", private_ip: "{{ terraform_output['outputs']['db-master-private-ip']['value'] }}", groups: "db-master" }
    - { hostname: "{{ terraform_output['outputs']['db-slave-public-ip']['value'] }}", private_ip: "{{ terraform_output['outputs']['db-slave-private-ip']['value'] }}", groups: "db-slave" }

- name: "Save a network acl id"
  set_fact:
    vpc-default-network-acl-id: "{{ terraform_output['outputs']['vpc-default-network-acl-id']['value'] }}"