- name: "Copy docker-compose"
  template:
    src: "{{ tpl_prefix }}-docker-compose.yml.j2"
    dest: "docker-compose/docker-compose.yml"

- name: "Execute docker-compose"
  shell:
    cmd: "docker-compose up -d --force-recreate"
    chdir: "docker-compose/"